{% set name = "azure-storage-blob" %}
{% set version = "12.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: f8b8d582492740ab16744455408342fb8e4c8897b64a8a3fc31743844722c2f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - isodate >=0.6.1
    - typing-extensions >=4.0.1
    - python >=3.6
    - azure-core <2.0.0,>=1.26.0
    - cryptography >=2.1.4
    - msrest >=0.7.1

test:
  imports:
    - azure.storage.blob
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/azure-storage-blob/
  summary: Microsoft Azure Blob Storage Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - xhochy
