{% set name = "azure-storage-blob" %}
{% set version = "12.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: cff66a115c73c90e496c8c8b3026898a3ce64100840276e9245434e28a864225

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - azure-core <2.0.0,>=1.9.0
    - cryptography >=2.1.4
    - msrest >=0.6.10

test:
  imports:
    - azure.storage.blob
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/azure-storage-blob/
  summary: Microsoft Azure Blob Storage Client Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dhirschfeld
    - xhochy
