{% set name = "azure-storage-blob" %}
{% set version = "12.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: a72dd9923e4b38a552f2bc1749d1fa5b820f497a8fb3cd2d77e7045bbe87bb4d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - azure-core <2.0.0,>=1.24.2
    - cryptography >=2.1.4
    - msrest >=0.7.1

test:
  imports:
    - azure.storage.blob
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/azure-storage-blob/
  summary: Microsoft Azure Blob Storage Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - xhochy
